export const ADD_MOVIE = "/add-movie";
export const DASHBOARD = "/dashboard";
export const LOGIN = "/login";
export const MOVIE = id => `/movie/${id}`;
export const MOVIE_DETAILS = "/movie/:id";
export const MOVIES = "/movies";
export const NOT_FOUND = "*";
export const ROOT = "/";
export const SIGNUP = "/signup";
export const USER = "/user";
